[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/product"
  to = "/product.html"
  status = 200

[[redirects]]
  from = "/collection"
  to = "/collection.html"
  status = 200
